on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Alwaysdata
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY:        ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST:            ${{ secrets.REMOTE_HOST }}
          REMOTE_USER:            ${{ secrets.REMOTE_USER }}
          REMOTE_PORT:            22
          SSH_CMD_ARGS:           "-o StrictHostKeyChecking=no -v -o IdentitiesOnly=yes"
          ARGS:                   "-rlgoDzvc --delete"
          SCRIPT_BEFORE:          "unset SSH_AUTH_SOCK"
          # paths to exclude separated by `,`, ie: `/dist/, /node_modules/`
          EXCLUDE: /.git/, /.github/, /.gitignore, /compose.override.yaml, /.env
          SCRIPT_BEFORE_REQUIRED: true
#      - name: Install dependencies
#        run: composer install
